services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --spi-theme-static-max-age=-1
      
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8080:8080"
    volumes:
      - ./themes/example:/opt/keycloak/themes/example